services:
  book_scraper:
    build:
      context: .

    container_name: book_scraper_ct

    volumes:
      - ".:/app"

    working_dir: /app

    command: bash

    stdin_open: true
    
    tty: true
